"""Seed the TRM database with 105+ realistic entries."""
import sys
import os

sys.path.insert(0, os.path.dirname(__file__))

from datetime import date
from app.database import SessionLocal, engine
from app.models import TRMEntry
from app import database

database.Base.metadata.create_all(bind=engine)

# Today is ~May 2026; EOL dates are set relative to that for realistic demo data.
TRM_SEED_DATA = [
    # -------------------------------------------------------------------------
    # Java / Spring – DataPlatform
    # -------------------------------------------------------------------------
    {
        "application": "DataPlatform",
        "tool_name": "Spring Boot",
        "current_version": "3.4.1",
        "latest_version": "3.4.5",
        "active": True,
        "open_source": True,
        "product_eol": date(2027, 2, 21),
        "eol_url": "https://spring.io/projects/spring-boot#support",
        "gsa_gear_url": None,
        "download_url": "https://spring.io/projects/spring-boot",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Core Java application framework for microservices",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Spring Framework",
        "current_version": "6.2.3",
        "latest_version": "6.2.5",
        "active": True,
        "open_source": True,
        "product_eol": date(2027, 2, 21),
        "eol_url": "https://spring.io/projects/spring-framework#support",
        "gsa_gear_url": None,
        "download_url": "https://spring.io/projects/spring-framework",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Foundational Spring Framework dependency",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Spring Security",
        "current_version": "6.3.3",
        "latest_version": "6.3.5",
        "active": True,
        "open_source": True,
        "product_eol": date(2027, 2, 21),
        "eol_url": "https://spring.io/projects/spring-security#support",
        "gsa_gear_url": None,
        "download_url": "https://spring.io/projects/spring-security",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Authentication and authorization framework",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Spring Data JPA",
        "current_version": "3.4.1",
        "latest_version": "3.4.3",
        "active": True,
        "open_source": True,
        "product_eol": date(2027, 2, 21),
        "eol_url": "https://spring.io/projects/spring-data-jpa#support",
        "gsa_gear_url": None,
        "download_url": "https://spring.io/projects/spring-data-jpa",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "JPA-based data access layer",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Hibernate ORM",
        "current_version": "6.6.4",
        "latest_version": "6.6.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://hibernate.org/orm/releases/",
        "gsa_gear_url": None,
        "download_url": "https://hibernate.org/orm/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "ORM framework for database persistence",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Jackson Databind",
        "current_version": "2.17.2",
        "latest_version": "2.18.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/FasterXML/jackson-databind",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "JSON serialization/deserialization library",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Jackson Core",
        "current_version": "2.17.2",
        "latest_version": "2.18.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/FasterXML/jackson-core",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Core streaming API for Jackson JSON processing",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Log4j2",
        "current_version": "2.23.1",
        "latest_version": "2.24.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://logging.apache.org/log4j/2.x/download.html",
        "gsa_gear_url": None,
        "download_url": "https://logging.apache.org/log4j/2.x/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": True,
        "aor_date": date(2022, 1, 15),
        "notes": "Logging framework; Log4Shell CVE-2021-44228 patched in 2.17+",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "SLF4J",
        "current_version": "2.0.16",
        "latest_version": "2.0.16",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.slf4j.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Simple Logging Facade for Java",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Logback",
        "current_version": "1.5.12",
        "latest_version": "1.5.15",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://logback.qos.ch/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Logging backend for SLF4J",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Lombok",
        "current_version": "1.18.36",
        "latest_version": "1.18.36",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://projectlombok.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Compile-time annotation processor to reduce boilerplate",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Guava",
        "current_version": "33.3.0",
        "latest_version": "33.4.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/google/guava",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Google core Java utilities library",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Apache Commons Lang",
        "current_version": "3.17.0",
        "latest_version": "3.17.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://commons.apache.org/proper/commons-lang/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "String manipulation and reflection utilities",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Apache Commons IO",
        "current_version": "2.18.0",
        "latest_version": "2.18.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://commons.apache.org/proper/commons-io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "IO utility library",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Apache Commons Collections",
        "current_version": "4.4",
        "latest_version": "4.5.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://commons.apache.org/proper/commons-collections/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Extended Java collections framework",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "HikariCP",
        "current_version": "6.2.1",
        "latest_version": "6.2.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/brettwooldridge/HikariCP",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "High-performance JDBC connection pool",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "PostgreSQL JDBC Driver",
        "current_version": "42.7.4",
        "latest_version": "42.7.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://jdbc.postgresql.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "JDBC driver for PostgreSQL",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Flyway",
        "current_version": "11.3.4",
        "latest_version": "11.4.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://flywaydb.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Database schema migration tool",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Micrometer",
        "current_version": "1.14.4",
        "latest_version": "1.14.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://micrometer.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Application metrics facade for JVM-based apps",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Resilience4j",
        "current_version": "2.3.0",
        "latest_version": "2.3.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://resilience4j.readme.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Fault tolerance library (circuit breaker, retry, rate limiter)",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "MapStruct",
        "current_version": "1.6.3",
        "latest_version": "1.6.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://mapstruct.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Code generation for bean mapping",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Apache Kafka Client (Java)",
        "current_version": "3.8.1",
        "latest_version": "3.9.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://kafka.apache.org/downloads",
        "gsa_gear_url": None,
        "download_url": "https://kafka.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Java client for producing/consuming Kafka messages",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "AWS SDK Java v2",
        "current_version": "2.29.35",
        "latest_version": "2.30.10",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://aws.amazon.com/sdk-for-java/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "AWS SDK for Java v2 – S3, Secrets Manager, MSK IAM auth",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Netty",
        "current_version": "4.1.116",
        "latest_version": "4.1.118",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://netty.io/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/detail/CVE-2024-29025",
        "aor_submitted": True,
        "aor_date": date(2024, 4, 10),
        "notes": "Async networking framework; CVE-2024-29025 – upgrade to 4.1.118+",
        "managed_by": "Platform Team",
    },
    {
        "application": "DataPlatform",
        "tool_name": "Caffeine Cache",
        "current_version": "3.2.0",
        "latest_version": "3.2.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/ben-manes/caffeine",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "High-performance caching library for Java",
        "managed_by": "Platform Team",
    },
    # -------------------------------------------------------------------------
    # Java – Analytics API / Reporting Service
    # -------------------------------------------------------------------------
    {
        "application": "Analytics API",
        "tool_name": "JUnit 5",
        "current_version": "5.11.4",
        "latest_version": "5.11.4",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://junit.org/junit5/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Unit testing framework for Java",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Mockito",
        "current_version": "5.14.2",
        "latest_version": "5.15.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://site.mockito.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Mocking framework for unit tests",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "SpringDoc OpenAPI",
        "current_version": "2.7.0",
        "latest_version": "2.8.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://springdoc.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "OpenAPI 3 / Swagger UI integration for Spring Boot",
        "managed_by": "Platform Team",
    },
    {
        "application": "Reporting Service",
        "tool_name": "Apache Tomcat",
        "current_version": "11.0.2",
        "latest_version": "11.0.4",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://tomcat.apache.org/whichversion.html",
        "gsa_gear_url": None,
        "download_url": "https://tomcat.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Servlet container / embedded web server for Spring Boot",
        "managed_by": "Platform Team",
    },
    {
        "application": "Reporting Service",
        "tool_name": "Quartz Scheduler",
        "current_version": "2.3.2",
        "latest_version": "2.5.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.quartz-scheduler.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Job scheduling library; upgrade to 2.5.0 for Java 17+ support",
        "managed_by": "Platform Team",
    },
    {
        "application": "Reporting Service",
        "tool_name": "OpenTelemetry Java Agent",
        "current_version": "2.10.0",
        "latest_version": "2.12.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://opentelemetry.io/docs/languages/java/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Auto-instrumentation agent for distributed tracing and metrics",
        "managed_by": "SRE Team",
    },
    # -------------------------------------------------------------------------
    # Java Build / Runtime
    # -------------------------------------------------------------------------
    {
        "application": "Infrastructure",
        "tool_name": "Maven",
        "current_version": "3.9.9",
        "latest_version": "3.9.9",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://maven.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Java build and dependency management tool",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Gradle",
        "current_version": "8.12",
        "latest_version": "8.13",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://gradle.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Build automation tool used for Android and DataPlatform modules",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "OpenJDK 17 LTS",
        "current_version": "17.0.13",
        "latest_version": "17.0.14",
        "active": True,
        "open_source": True,
        "product_eol": date(2026, 9, 30),
        "eol_url": "https://endoflife.date/java",
        "gsa_gear_url": None,
        "download_url": "https://adoptium.net/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "JDK runtime for DataPlatform and Reporting Service – EOL Sep 2026, plan upgrade to JDK 21",
        "managed_by": "Platform Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "OpenJDK 21 LTS",
        "current_version": "21.0.5",
        "latest_version": "21.0.6",
        "active": True,
        "open_source": True,
        "product_eol": date(2028, 9, 30),
        "eol_url": "https://endoflife.date/java",
        "gsa_gear_url": None,
        "download_url": "https://adoptium.net/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Target JDK for all new Java services",
        "managed_by": "Platform Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "OpenJDK 11 LTS",
        "current_version": "11.0.25",
        "latest_version": "11.0.25",
        "active": False,
        "open_source": True,
        "product_eol": date(2024, 10, 31),
        "eol_url": "https://endoflife.date/java",
        "gsa_gear_url": None,
        "download_url": "https://adoptium.net/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/search/results?query=openjdk+11",
        "aor_submitted": True,
        "aor_date": date(2024, 11, 15),
        "notes": "PAST EOL – October 2024. Decommissioned; legacy service still running on this version",
        "managed_by": "Platform Team",
    },
    # -------------------------------------------------------------------------
    # Python Core
    # -------------------------------------------------------------------------
    {
        "application": "Analytics API",
        "tool_name": "Python 3.12",
        "current_version": "3.12.8",
        "latest_version": "3.12.9",
        "active": True,
        "open_source": True,
        "product_eol": date(2028, 10, 31),
        "eol_url": "https://endoflife.date/python",
        "gsa_gear_url": None,
        "download_url": "https://www.python.org/downloads/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Primary Python runtime for Analytics API",
        "managed_by": "Platform Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "Python 3.11",
        "current_version": "3.11.11",
        "latest_version": "3.11.12",
        "active": True,
        "open_source": True,
        "product_eol": date(2027, 10, 24),
        "eol_url": "https://endoflife.date/python",
        "gsa_gear_url": None,
        "download_url": "https://www.python.org/downloads/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Python runtime for ML Pipeline; plan upgrade to 3.12 by Q4 2026",
        "managed_by": "ML Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Python 3.10",
        "current_version": "3.10.16",
        "latest_version": "3.10.16",
        "active": True,
        "open_source": True,
        "product_eol": date(2026, 10, 4),
        "eol_url": "https://endoflife.date/python",
        "gsa_gear_url": None,
        "download_url": "https://www.python.org/downloads/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data Ingestion service runtime – EOL October 2026, upgrade scheduled Q3 2026",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Python 3.9",
        "current_version": "3.9.21",
        "latest_version": "3.9.21",
        "active": False,
        "open_source": True,
        "product_eol": date(2025, 10, 5),
        "eol_url": "https://endoflife.date/python",
        "gsa_gear_url": None,
        "download_url": "https://www.python.org/downloads/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/search/results?query=python+3.9",
        "aor_submitted": True,
        "aor_date": date(2025, 11, 1),
        "notes": "PAST EOL – Oct 2025. Legacy Airflow DAG runtime; migration to 3.12 in progress",
        "managed_by": "Data Engineering Team",
    },
    # -------------------------------------------------------------------------
    # Python – FastAPI / Analytics API
    # -------------------------------------------------------------------------
    {
        "application": "Analytics API",
        "tool_name": "FastAPI",
        "current_version": "0.115.6",
        "latest_version": "0.115.9",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://fastapi.tiangolo.com/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "High-performance async web framework for the Analytics REST API",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Pydantic",
        "current_version": "2.10.4",
        "latest_version": "2.10.6",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://docs.pydantic.dev/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data validation library used with FastAPI",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Uvicorn",
        "current_version": "0.34.0",
        "latest_version": "0.34.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.uvicorn.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "ASGI server for running FastAPI in production",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Gunicorn",
        "current_version": "23.0.0",
        "latest_version": "23.0.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://gunicorn.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Process manager running Uvicorn workers in production",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "SQLAlchemy",
        "current_version": "2.0.36",
        "latest_version": "2.0.38",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.sqlalchemy.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Python SQL toolkit and ORM",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Alembic",
        "current_version": "1.14.0",
        "latest_version": "1.14.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://alembic.sqlalchemy.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Database schema migration tool for SQLAlchemy",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Requests",
        "current_version": "2.32.3",
        "latest_version": "2.32.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://docs.python-requests.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "HTTP library for API calls to external services",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "HTTPX",
        "current_version": "0.28.1",
        "latest_version": "0.28.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.python-httpx.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Async HTTP client for FastAPI async contexts",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "pytest",
        "current_version": "8.3.4",
        "latest_version": "8.3.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://pytest.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Python testing framework",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "PyYAML",
        "current_version": "6.0.2",
        "latest_version": "6.0.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://pyyaml.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "YAML parsing library for configuration files",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "python-dotenv",
        "current_version": "1.0.1",
        "latest_version": "1.0.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://github.com/theskumar/python-dotenv",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Environment variable management from .env files",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "marshmallow",
        "current_version": "3.23.1",
        "latest_version": "3.23.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://marshmallow.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Object serialization/deserialization library",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "tenacity",
        "current_version": "8.5.0",
        "latest_version": "9.0.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://tenacity.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "General-purpose retrying library for Python",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "structlog",
        "current_version": "24.4.0",
        "latest_version": "25.1.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.structlog.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Structured logging library for Python",
        "managed_by": "Platform Team",
    },
    # -------------------------------------------------------------------------
    # Python – ML Pipeline
    # -------------------------------------------------------------------------
    {
        "application": "ML Pipeline",
        "tool_name": "Pandas",
        "current_version": "2.2.3",
        "latest_version": "2.2.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://pandas.pydata.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data manipulation and analysis library",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "NumPy",
        "current_version": "2.2.1",
        "latest_version": "2.2.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://numpy.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Numerical computation library for Python",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "Scikit-learn",
        "current_version": "1.6.1",
        "latest_version": "1.6.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://scikit-learn.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Machine learning library for Python",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "Matplotlib",
        "current_version": "3.10.0",
        "latest_version": "3.10.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://matplotlib.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Plotting and visualization library",
        "managed_by": "ML Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "Plotly",
        "current_version": "5.24.1",
        "latest_version": "5.24.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://plotly.com/python/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Interactive visualization library used in reports",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "PyArrow",
        "current_version": "18.1.0",
        "latest_version": "19.0.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://arrow.apache.org/docs/python/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Apache Arrow Python binding for columnar data interchange",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "boto3",
        "current_version": "1.35.89",
        "latest_version": "1.36.25",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://boto3.amazonaws.com/v1/documentation/api/latest/index.html",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "AWS SDK for Python – S3, SageMaker, Secrets Manager",
        "managed_by": "ML Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "psycopg2",
        "current_version": "2.9.10",
        "latest_version": "2.9.10",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.psycopg.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "PostgreSQL adapter for Python",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "redis-py",
        "current_version": "5.2.1",
        "latest_version": "5.2.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://redis-py.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Python client for Redis caching layer",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "cryptography",
        "current_version": "44.0.0",
        "latest_version": "44.0.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://cryptography.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Cryptographic primitives and recipes for Python",
        "managed_by": "Platform Team",
    },
    # -------------------------------------------------------------------------
    # Python – Airflow / Data Ingestion
    # -------------------------------------------------------------------------
    {
        "application": "Data Ingestion",
        "tool_name": "Apache Airflow",
        "current_version": "2.10.4",
        "latest_version": "2.10.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://airflow.apache.org/docs/apache-airflow/stable/release-process.html",
        "gsa_gear_url": None,
        "download_url": "https://airflow.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Workflow orchestration platform for ETL pipelines",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Celery",
        "current_version": "5.4.0",
        "latest_version": "5.5.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://docs.celeryq.dev/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Distributed task queue for async workloads",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "kafka-python",
        "current_version": "2.0.2",
        "latest_version": "2.0.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://kafka-python.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Python client library for Apache Kafka",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Apache Airflow Provider – AWS",
        "current_version": "8.27.0",
        "latest_version": "8.30.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://airflow.apache.org/docs/apache-airflow-providers-amazon/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Airflow operators and hooks for AWS services (S3, MSK, RDS)",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Apache Airflow Provider – Postgres",
        "current_version": "5.14.0",
        "latest_version": "5.15.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://airflow.apache.org/docs/apache-airflow-providers-postgres/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Airflow operators and hooks for PostgreSQL",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Great Expectations",
        "current_version": "1.3.2",
        "latest_version": "1.4.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://greatexpectations.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data quality validation framework for pipeline assertions",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "dbt-core",
        "current_version": "1.9.3",
        "latest_version": "1.9.4",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://docs.getdbt.com/docs/dbt-versions/core",
        "gsa_gear_url": None,
        "download_url": "https://docs.getdbt.com/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "SQL-based data transformation tool",
        "managed_by": "Data Engineering Team",
    },
    # -------------------------------------------------------------------------
    # Python – Jupyter / ML Platform
    # -------------------------------------------------------------------------
    {
        "application": "ML Pipeline",
        "tool_name": "JupyterLab",
        "current_version": "4.3.4",
        "latest_version": "4.3.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://jupyter-notebook.readthedocs.io/en/stable/changelog.html",
        "gsa_gear_url": None,
        "download_url": "https://jupyter.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Interactive development environment for data science notebooks",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "Jupyter Notebook",
        "current_version": "7.3.2",
        "latest_version": "7.3.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://jupyter.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Classic notebook interface; JupyterLab is the preferred interface",
        "managed_by": "ML Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "ipykernel",
        "current_version": "6.29.5",
        "latest_version": "6.29.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://ipython.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "IPython kernel for Jupyter notebooks",
        "managed_by": "ML Team",
    },
    # -------------------------------------------------------------------------
    # Python – Security / Auth
    # -------------------------------------------------------------------------
    {
        "application": "Analytics API",
        "tool_name": "python-jose",
        "current_version": "3.3.0",
        "latest_version": "3.3.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://python-jose.readthedocs.io/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/detail/CVE-2024-33663",
        "aor_submitted": True,
        "aor_date": date(2024, 6, 1),
        "notes": "JWT implementation; CVE-2024-33663 – consider migrating to PyJWT",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "passlib",
        "current_version": "1.7.4",
        "latest_version": "1.7.4",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://passlib.readthedocs.io/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/search/results?query=passlib",
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Password hashing library; project appears unmaintained – evaluate argon2-cffi",
        "managed_by": "Platform Team",
    },
    {
        "application": "Analytics API",
        "tool_name": "fastapi-users",
        "current_version": "13.0.0",
        "latest_version": "13.0.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://fastapi-users.github.io/fastapi-users/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "User management / auth library for FastAPI",
        "managed_by": "Platform Team",
    },
    # -------------------------------------------------------------------------
    # Apache Kafka Ecosystem
    # -------------------------------------------------------------------------
    {
        "application": "Infrastructure",
        "tool_name": "Apache Kafka",
        "current_version": "3.8.1",
        "latest_version": "3.9.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://kafka.apache.org/downloads",
        "gsa_gear_url": None,
        "download_url": "https://kafka.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Distributed event streaming platform; self-managed clusters",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "AWS MSK (Apache Kafka)",
        "current_version": "3.7.x",
        "latest_version": "3.8.x",
        "active": True,
        "open_source": False,
        "product_eol": None,
        "eol_url": "https://docs.aws.amazon.com/msk/latest/developerguide/supported-kafka-versions.html",
        "gsa_gear_url": None,
        "download_url": "https://aws.amazon.com/msk/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Managed Kafka service on AWS; production event bus",
        "managed_by": "SRE Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Kafka Connect",
        "current_version": "3.8.1",
        "latest_version": "3.9.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://kafka.apache.org/documentation/#connect",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Framework for connecting Kafka to databases and external systems",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Confluent Schema Registry",
        "current_version": "7.8.0",
        "latest_version": "7.8.1",
        "active": True,
        "open_source": False,
        "product_eol": None,
        "eol_url": "https://docs.confluent.io/platform/current/release-notes/index.html",
        "gsa_gear_url": None,
        "download_url": "https://www.confluent.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Schema registry for Avro/JSON/Protobuf schema management",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Apache Avro",
        "current_version": "1.12.0",
        "latest_version": "1.12.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://avro.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data serialization format used for Kafka messages",
        "managed_by": "Data Engineering Team",
    },
    # -------------------------------------------------------------------------
    # Databases
    # -------------------------------------------------------------------------
    {
        "application": "Infrastructure",
        "tool_name": "AWS RDS Aurora PostgreSQL",
        "current_version": "16.4",
        "latest_version": "16.6",
        "active": True,
        "open_source": False,
        "product_eol": date(2028, 11, 12),
        "eol_url": "https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/Aurora.VersionPolicy.html",
        "gsa_gear_url": None,
        "download_url": "https://aws.amazon.com/rds/aurora/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Primary transactional database; multi-AZ cluster in us-east-1",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "PostgreSQL",
        "current_version": "16.6",
        "latest_version": "17.2",
        "active": True,
        "open_source": True,
        "product_eol": date(2028, 11, 9),
        "eol_url": "https://www.postgresql.org/support/versioning/",
        "gsa_gear_url": None,
        "download_url": "https://www.postgresql.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Open-source relational database; used for dev/staging environments",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Redis",
        "current_version": "7.4.2",
        "latest_version": "7.4.2",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://endoflife.date/redis",
        "gsa_gear_url": None,
        "download_url": "https://redis.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "In-memory data store for caching and session management",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Apache ZooKeeper",
        "current_version": "3.9.3",
        "latest_version": "3.9.3",
        "active": False,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://zookeeper.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Decommissioned; Kafka migrated to KRaft mode (ZooKeeper-less)",
        "managed_by": "SRE Team",
    },
    # -------------------------------------------------------------------------
    # Observability Stack
    # -------------------------------------------------------------------------
    {
        "application": "Infrastructure",
        "tool_name": "Prometheus",
        "current_version": "3.1.0",
        "latest_version": "3.1.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://prometheus.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Metrics collection and alerting",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Grafana",
        "current_version": "11.4.0",
        "latest_version": "11.5.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://grafana.com/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Metrics and log visualization dashboards",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Elasticsearch",
        "current_version": "8.17.1",
        "latest_version": "8.17.3",
        "active": True,
        "open_source": False,
        "product_eol": date(2027, 2, 28),
        "eol_url": "https://www.elastic.co/support/eol",
        "gsa_gear_url": None,
        "download_url": "https://www.elastic.co/elasticsearch/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Search and analytics engine for log aggregation",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Logstash",
        "current_version": "8.17.1",
        "latest_version": "8.17.3",
        "active": True,
        "open_source": False,
        "product_eol": date(2027, 2, 28),
        "eol_url": "https://www.elastic.co/support/eol",
        "gsa_gear_url": None,
        "download_url": "https://www.elastic.co/logstash/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Log ingestion pipeline (ELK stack)",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Kibana",
        "current_version": "8.17.1",
        "latest_version": "8.17.3",
        "active": True,
        "open_source": False,
        "product_eol": date(2027, 2, 28),
        "eol_url": "https://www.elastic.co/support/eol",
        "gsa_gear_url": None,
        "download_url": "https://www.elastic.co/kibana/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Log visualization and search UI (ELK stack)",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "OpenTelemetry Collector",
        "current_version": "0.116.0",
        "latest_version": "0.118.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://opentelemetry.io/docs/collector/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Vendor-agnostic telemetry collection (traces, metrics, logs)",
        "managed_by": "SRE Team",
    },
    # -------------------------------------------------------------------------
    # Container / Platform Infrastructure
    # -------------------------------------------------------------------------
    {
        "application": "Infrastructure",
        "tool_name": "Docker",
        "current_version": "27.4.1",
        "latest_version": "27.5.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://docs.docker.com/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Container runtime for local development and CI builds",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Kubernetes",
        "current_version": "1.32.1",
        "latest_version": "1.33.0",
        "active": True,
        "open_source": True,
        "product_eol": date(2026, 8, 28),
        "eol_url": "https://endoflife.date/kubernetes",
        "gsa_gear_url": None,
        "download_url": "https://kubernetes.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "EKS cluster container orchestration – upgrade to 1.33 planned Q3 2026",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Helm",
        "current_version": "3.16.4",
        "latest_version": "3.17.1",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://helm.sh/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Kubernetes package manager for chart-based deployments",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Nginx",
        "current_version": "1.27.3",
        "latest_version": "1.27.4",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://nginx.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Reverse proxy and ingress controller",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "HashiCorp Vault",
        "current_version": "1.18.3",
        "latest_version": "1.19.0",
        "active": True,
        "open_source": False,
        "product_eol": None,
        "eol_url": "https://support.hashicorp.com/hc/en-us/articles/360021185113",
        "gsa_gear_url": None,
        "download_url": "https://www.vaultproject.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Secrets management and dynamic credential generation",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Terraform",
        "current_version": "1.10.3",
        "latest_version": "1.11.0",
        "active": True,
        "open_source": False,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.terraform.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Infrastructure-as-code for AWS resource provisioning",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Jenkins",
        "current_version": "2.491",
        "latest_version": "2.497",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://www.jenkins.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "CI/CD automation server",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "ArgoCD",
        "current_version": "2.13.3",
        "latest_version": "2.14.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://argo-cd.readthedocs.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "GitOps continuous delivery tool for Kubernetes",
        "managed_by": "DevOps Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Istio",
        "current_version": "1.24.2",
        "latest_version": "1.24.3",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://istio.io/latest/docs/releases/supported-releases/",
        "gsa_gear_url": None,
        "download_url": "https://istio.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Service mesh for mTLS, traffic management, and observability",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "MinIO",
        "current_version": "RELEASE.2025-01-20",
        "latest_version": "RELEASE.2025-03-12",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://min.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "S3-compatible object storage for local dev and ML model artifacts",
        "managed_by": "SRE Team",
    },
    # -------------------------------------------------------------------------
    # Data Platform Tools
    # -------------------------------------------------------------------------
    {
        "application": "Data Ingestion",
        "tool_name": "Apache NiFi",
        "current_version": "2.1.0",
        "latest_version": "2.2.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://nifi.apache.org/downloads/",
        "gsa_gear_url": None,
        "download_url": "https://nifi.apache.org/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/detail/CVE-2024-37389",
        "aor_submitted": True,
        "aor_date": date(2024, 8, 5),
        "notes": "Data flow automation; CVE-2024-37389 patched in 2.0.0+",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Open Data Discovery (ODD)",
        "current_version": "0.19.0",
        "latest_version": "0.20.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://opendatadiscovery.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Data catalog and data discovery platform",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Keycloak",
        "current_version": "26.0.7",
        "latest_version": "26.1.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": "https://www.keycloak.org/support",
        "gsa_gear_url": None,
        "download_url": "https://www.keycloak.org/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/detail/CVE-2024-1132",
        "aor_submitted": True,
        "aor_date": date(2024, 3, 20),
        "notes": "Identity and access management; CVE-2024-1132 – upgrade to 24.0.3+",
        "managed_by": "SRE Team",
    },
    {
        "application": "Infrastructure",
        "tool_name": "Apache Spark",
        "current_version": "3.5.1",
        "latest_version": "3.5.5",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://spark.apache.org/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Distributed data processing engine for large-scale analytics",
        "managed_by": "Data Engineering Team",
    },
    {
        "application": "ML Pipeline",
        "tool_name": "Delta Lake",
        "current_version": "3.2.1",
        "latest_version": "3.3.0",
        "active": True,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://delta.io/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Open-source storage layer for reliable data lakes on S3",
        "managed_by": "ML Team",
    },
    # -------------------------------------------------------------------------
    # Legacy / Deprecated entries (for realistic EOL demo data)
    # -------------------------------------------------------------------------
    {
        "application": "Reporting Service",
        "tool_name": "Spring Boot (Legacy)",
        "current_version": "2.7.18",
        "latest_version": "3.4.5",
        "active": False,
        "open_source": True,
        "product_eol": date(2023, 11, 24),
        "eol_url": "https://spring.io/projects/spring-boot#support",
        "gsa_gear_url": None,
        "download_url": "https://spring.io/projects/spring-boot",
        "has_vulnerabilities": True,
        "cve_report_link": "https://spring.io/security/cve-2023-34055",
        "aor_submitted": True,
        "aor_date": date(2023, 12, 15),
        "notes": "PAST EOL – Nov 2023. Legacy reporting module pending migration to Spring Boot 3.4",
        "managed_by": "Platform Team",
    },
    {
        "application": "Data Ingestion",
        "tool_name": "Django",
        "current_version": "4.2.16",
        "latest_version": "5.1.5",
        "active": False,
        "open_source": True,
        "product_eol": date(2026, 4, 30),
        "eol_url": "https://www.djangoproject.com/download/#supported-versions",
        "gsa_gear_url": None,
        "download_url": "https://www.djangoproject.com/",
        "has_vulnerabilities": True,
        "cve_report_link": "https://nvd.nist.gov/vuln/detail/CVE-2024-27351",
        "aor_submitted": True,
        "aor_date": date(2026, 5, 1),
        "notes": "PAST EOL – April 30 2026. Admin portal; replacement with FastAPI in progress",
        "managed_by": "Platform Team",
    },
    {
        "application": "Reporting Service",
        "tool_name": "Flask",
        "current_version": "2.3.3",
        "latest_version": "3.1.0",
        "active": False,
        "open_source": True,
        "product_eol": None,
        "eol_url": None,
        "gsa_gear_url": None,
        "download_url": "https://flask.palletsprojects.com/",
        "has_vulnerabilities": False,
        "cve_report_link": None,
        "aor_submitted": False,
        "aor_date": None,
        "notes": "Decommissioned lightweight reporting API; replaced by FastAPI service",
        "managed_by": "Platform Team",
    },
]


def seed():
    db = SessionLocal()
    try:
        existing = db.query(TRMEntry).count()
        if existing > 0:
            print(f"Database already contains {existing} entries. Skipping seed.")
            return

        print(f"Seeding {len(TRM_SEED_DATA)} TRM entries...")
        for data in TRM_SEED_DATA:
            entry = TRMEntry(**data)
            db.add(entry)
        db.commit()
        print(f"Successfully seeded {len(TRM_SEED_DATA)} entries.")
    except Exception as e:
        db.rollback()
        print(f"Seed failed: {e}")
        raise
    finally:
        db.close()


if __name__ == "__main__":
    seed()
